package org.example.events;

public enum EventType {

    FLOOR_DISPATCH_EVENT,
    IN_ELEVATOR_DISPATCH_EVENT,
    START_SIMULATION,
    STOP_SIMULATION,
    PAUSE_SIMULATION,
    RESUME_SIMULATION,
    FORWARD_SIMULATION,
    UPDATE_SIMULATION,
    EMIT_EVENT_SIMULATION,
    FETCH_STATES_SIMULATION,
    START_RANDOM_EVENT_EMITTER,
    STOP_RANDOM_EVENT_EMITTER

}
